services:
  app:
    build:
      context: .
      dockerfile: .docker/bun/Dockerfile
      args:
        BUN_IMAGE: ${BUN_IMAGE}
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: bun run dev
    depends_on:
      - db
  db:
    build:
      context: .docker/mysql
      args:
        MYSQL_IMAGE: ${MYSQL_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql/data:/var/lib/mysql
